### PR TITLE
#1 Basic Outline

### PR DESCRIPTION
**Pull request by alexlehuynh**
Basic outline with 3 divs for input argument and output.

### CODE REVIEW

**Comment by choudhs2** [comment]
I cleaned it up with CSS and made a button, I think that one is better commit

**Comment by alexlehuynh** [comment]
Looks good, thank you for cleaning it up, looks a lot better now!

**Comment by Hasnain-commits** [comment]
I don't understand. But push it to prod 💪💪💪💪💪💪💪

**Comment by wy33** [comment]
praise: looks better than what I can come up with =), push to prod!

**Pull request merged**
